//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Returns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_Returns()
        {
            this.Customers_Returns_Orders = new HashSet<Customers_Returns_Orders>();
        }
    
        public int Cust_Return_ID { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> Total_amount { get; set; }
        public Nullable<System.DateTime> return_Date { get; set; }
        public Nullable<int> c_Return_Code { get; set; }
        public string Customer_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Returns_Orders> Customers_Returns_Orders { get; set; }
    }
}
