//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Customers_Returns_Orders = new HashSet<Customers_Returns_Orders>();
            this.Orders = new HashSet<Order>();
            this.Return_Supplier_Invoices = new HashSet<Return_Supplier_Invoices>();
            this.Supplier_Invoices = new HashSet<Supplier_Invoices>();
        }
    
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string National_ID { get; set; }
        public string Gender { get; set; }
        public string Employee_Address { get; set; }
        public string Employee_Phone { get; set; }
        public string Employee_Email { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public string Employee_Shift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Returns_Orders> Customers_Returns_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Supplier_Invoices> Return_Supplier_Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Invoices> Supplier_Invoices { get; set; }

        public override string ToString()
        {
            return Employee_Name;
        }
    }
}
