//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Customers_Returns_Orders = new HashSet<Customers_Returns_Orders>();
            this.Products_Orders = new HashSet<Products_Orders>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<int> Total_Amount { get; set; }
        public Nullable<double> Total_price { get; set; }
        public string Order_Code { get; set; }
        public Nullable<System.DateTime> Sell_date { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Returns_Orders> Customers_Returns_Orders { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Orders> Products_Orders { get; set; }
    }
}
