//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Customers_Returns_Orders = new HashSet<Customers_Returns_Orders>();
            this.Supplier_Invoices_Products = new HashSet<Supplier_Invoices_Products>();
            this.Products_Orders = new HashSet<Products_Orders>();
            this.Quantity_Details = new HashSet<Quantity_Details>();
            this.Return_Supplier_Invoices_Products = new HashSet<Return_Supplier_Invoices_Products>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Price_Per_Unit { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Returns_Orders> Customers_Returns_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Invoices_Products> Supplier_Invoices_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Orders> Products_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quantity_Details> Quantity_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Supplier_Invoices_Products> Return_Supplier_Invoices_Products { get; set; }
    }
}
