//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Supplier_Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Return_Supplier_Invoices()
        {
            this.Return_Supplier_Invoices_Products = new HashSet<Return_Supplier_Invoices_Products>();
        }
    
        public int Return_Supplier_ID { get; set; }
        public Nullable<System.DateTime> Return_Supplier_Date { get; set; }
        public Nullable<double> Return_Price { get; set; }
        public Nullable<int> Return_Total_Amount { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Supplier_Note { get; set; }
        public string RS_Code { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Supplier_Invoices_Products> Return_Supplier_Invoices_Products { get; set; }
    }
}
