//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Invoices_Products
    {
        public int Supplier_ID { get; set; }
        public int Product_ID { get; set; }
        public int Supplier_Invoices_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier_Invoices Supplier_Invoices { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
