//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharm_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Invoices()
        {
            this.Return_Supplier_Invoices_Products = new HashSet<Return_Supplier_Invoices_Products>();
            this.Supplier_Invoices_Products = new HashSet<Supplier_Invoices_Products>();
        }
    
        public int Supplier_Invoices_ID { get; set; }
        public Nullable<double> S_Invoice_TotalAmount { get; set; }
        public Nullable<System.DateTime> S_Invoice_Date { get; set; }
        public Nullable<int> S_Invoice_code { get; set; }
        public Nullable<int> Suppliers_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Supplier_Invoices_Products> Return_Supplier_Invoices_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Invoices_Products> Supplier_Invoices_Products { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
